[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --tb=short
    --browser chromium
    --html=reports/html/report.html
    --self-contained-html
    --alluredir=reports/allure-results
    --headed
markers =
    smoke: 冒烟测试
    regression: 回归测试
